{% set name = "jcc" %}
{% set version = "3.3.dev1" %}
{% set sha256 = "5bf3d36045fd617f651d48f695af0cb2009d73cfca43810980aa1094377a37aa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://github.com/petrushy/jcc_svn_import/raw/master/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  skip: true  # [win32 or linux32]

  number: 0

  rpaths: # only valid for linux
    - lib
    - jre/lib/amd64/
    - jre/lib/amd64/server/

  has_prefix_files:
    - {{SP_DIR}}/jcc/config.py  # [linux or osx]

  # The JCC for windows package does not have the right compile parameters for wrapping and needs these to be set
  # explicitly


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - openjdk 8.0.152  # Force anaconda openjdk

  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - openjdk 8.0.152  # Force anaconda openjdk


test:
  # Some package might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - jcc

  files:
    - test/*.py
    - test/java-example/build_and_wrap.bat
    - test/java-example/build_and_wrap.sh
    - test/java-example/test1class.java

about:
  home: http://lucene.apache.org/pylucene/jcc/index.html

  license: Apache-2.0
  license_file: LICENSE

  summary: 'a C++ code generator for calling Java from C++/Python'
  description: |
    JCC is a C++ code generator for producing the code necessary to call into Java classes from CPython via Java’s Native Invocation Interface (JNI).

  doc_url: http://lucene.apache.org/pylucene/jcc/index.html

extra:
  recipe-maintainers:
    - petrushy
