{% set name = "JCC" %}
{% set version = "3.3" %}
{% set sha256 = "547a405b8ace0ffadd886b44259e95d8715d69e36f8d3fed00ee9ba127f3d4f2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/04/65/649b74f09c5f8db6cd142d07d4bac7b50b0ce0995174dfbb827e0a39ab9d/{{ name }}-{{ version }}.tar.gz

  sha256: {{ sha256 }}

build:
  skip: true  # [win32 or linux32]

  number: 1

  rpaths: # only valid for linux
    - lib
    - jre/lib/amd64/
    - jre/lib/amd64/server/

  has_prefix_files:
    - {{SP_DIR}}/jcc/config.py  # [linux or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - openjdk 8.0.152  # Force anaconda openjdk

  run:
    - python
    - openjdk 8.0.152  # Force anaconda openjdk

test:
  imports:
    - jcc

  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  files:
    - test/*.py
    - test/java-example/build_and_wrap.bat
    - test/java-example/build_and_wrap.sh
    - test/java-example/test1class.java

about:
  home: http://lucene.apache.org/pylucene/jcc/index.html

  license: Apache-2.0
  license_file: LICENSE

  summary: 'a C++ code generator for calling Java from C++/Python'
  description: |
    JCC is a C++ code generator for producing the code necessary to call into Java classes from CPython via Java’s Native Invocation Interface (JNI).

  doc_url: http://lucene.apache.org/pylucene/jcc/index.html

extra:
  recipe-maintainers:
    - petrushy
